# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='location_lat',
            field=models.CharField(default=b'null', max_length=300),
        ),
        migrations.AddField(
            model_name='customer',
            name='location_long',
            field=models.CharField(default=b'null', max_length=300),
        ),
    ]
