# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-20 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0002_auto_20181020_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='blood_group',
            field=models.CharField(default=b'null', max_length=4),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_id',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_id_friend_1',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_id_friend_2',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_id_friend_3',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AlterField(
            model_name='customer',
            name='medical_history',
            field=models.CharField(default=b'null', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(default=b'null', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default=b'null', max_length=400),
        ),
    ]
