# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-21 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0003_auto_20181020_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='disasterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disasterDescription', models.CharField(default=b'null', max_length=400)),
                ('disasterLocation', models.CharField(default=b'null', max_length=400)),
                ('disasterStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='isPersonSafe',
            field=models.BooleanField(default=True),
        ),
    ]
