# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0004_auto_20181021_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='disaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disasterName', models.CharField(default=b'null', max_length=200)),
                ('location', models.CharField(default=b'null', max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='disasterData',
        ),
    ]
