# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0006_auto_20181021_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='disasterIn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userData.disaster'),
        ),
    ]
