# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-21 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0007_customer_disasterin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='isPersonSafe',
        ),
        migrations.AddField(
            model_name='customer',
            name='isPersonInTrouble',
            field=models.BooleanField(default=False),
        ),
    ]
