# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-25 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0009_auto_20181021_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=b'null', max_length=600, null=True),
        ),
    ]
